"use client"

import { useState, useCallback } from "react"
import { Image as ImageIcon, X, Save } from "lucide-react"
import ReactMarkdown from "react-markdown"
import { useWorkspace } from "../workspace-provider"

export default function LessonEditor() {
  const [imageFile, setImageFile] = useState<File | null>(null)
  const [markdown, setMarkdown] = useState("")
  const [title, setTitle] = useState("")
  const [tags, setTags] = useState("")
  const { workspace } = useWorkspace()

  const handleImageDrop = useCallback((e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault()
    const droppedFile = e.dataTransfer.files[0]
    if (droppedFile && droppedFile.type.startsWith("image/")) {
      setImageFile(droppedFile)
    }
  }, [])

  return (
    <div className="grid md:grid-cols-2 gap-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
      {/* Editor Side */}
      <div className="bg-card border border-border rounded-2xl p-6 shadow-sm flex flex-col gap-5">
        <div>
          <h2 className="text-xl font-bold mb-1">Create New Lesson</h2>
          <p className="text-sm text-muted-foreground">Paste your Gem's Markdown output here.</p>
        </div>

        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium mb-1.5">Lesson Title</label>
            <input 
              type="text" 
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="e.g. Modern Mullet Step-by-step"
              className="w-full px-4 py-2 border border-border rounded-lg bg-background focus:ring-2 focus:ring-primary outline-none transition-all"
            />
          </div>

          <div>
            <label className="block text-sm font-medium mb-1.5">Reference Image (Generated by AI or Real)</label>
            {!imageFile ? (
              <div
                onDragOver={(e) => e.preventDefault()}
                onDrop={handleImageDrop}
                className="border-2 border-dashed border-border rounded-xl p-6 flex flex-col items-center justify-center bg-muted/30 hover:bg-muted/50 transition-colors cursor-pointer"
                onClick={() => document.getElementById("lesson-img-upload")?.click()}
              >
                <ImageIcon className="w-6 h-6 text-muted-foreground mb-2" />
                <p className="text-sm font-medium">Upload Image</p>
                <input
                  id="lesson-img-upload"
                  type="file"
                  accept="image/*"
                  className="hidden"
                  onChange={(e) => {
                    const file = e.target.files?.[0]
                    if (file) setImageFile(file)
                  }}
                />
              </div>
            ) : (
              <div className="relative rounded-xl overflow-hidden bg-muted aspect-video flex items-center justify-center">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img src={URL.createObjectURL(imageFile)} alt="Preview" className="object-cover w-full h-full" />
                <button
                  onClick={() => setImageFile(null)}
                  className="absolute top-2 right-2 bg-black/50 hover:bg-black text-white p-1.5 rounded-full backdrop-blur-sm"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>
            )}
          </div>

          <div>
            <label className="block text-sm font-medium mb-1.5">Lesson Markdown Content</label>
            <textarea
              value={markdown}
              onChange={(e) => setMarkdown(e.target.value)}
              placeholder="Paste the markdown here..."
              className="w-full h-[250px] p-4 bg-background border border-border rounded-xl text-sm focus:ring-2 focus:ring-primary outline-none resize-y font-mono"
            ></textarea>
          </div>

          <div>
            <label className="block text-sm font-medium mb-1.5">Tags (comma separated)</label>
            <input 
              type="text" 
              value={tags}
              onChange={(e) => setTags(e.target.value)}
              placeholder="e.g. mullet, texturizing, point-cutting"
              className="w-full px-4 py-2 border border-border rounded-lg bg-background focus:ring-2 focus:ring-primary outline-none transition-all"
            />
          </div>

          <button className="w-full bg-primary text-primary-foreground py-2.5 rounded-lg font-medium hover:opacity-90 transition-opacity">
            Save to {workspace === 'salon' ? 'Salon' : 'Barber'} Database
          </button>
        </div>
      </div>

      {/* Live Preview Side */}
      <div className="bg-neutral-900 rounded-2xl shadow-xl overflow-hidden flex flex-col h-[calc(100vh-140px)] sticky top-[88px]">
        <div className="p-4 bg-black/50 border-b border-white/10 flex justify-between items-center backdrop-blur-md">
          <h3 className="text-white font-medium flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
            Live Preview
          </h3>
          <button className="text-white/60 hover:text-white transition-colors" onClick={() => window.print()}>
            <Save className="w-4 h-4" />
          </button>
        </div>
        
        <div className="flex-1 overflow-y-auto p-6 lg:p-8 bg-white text-black" id="lesson-preview">
          {imageFile && (
            <div className="mb-8 rounded-2xl overflow-hidden shadow-lg border border-neutral-100 max-w-sm mx-auto">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src={URL.createObjectURL(imageFile)} alt="Final Hairstyle" className="w-full h-auto" />
            </div>
          )}
          
          {markdown ? (
            <div className="prose prose-neutral max-w-none prose-headings:font-bold prose-h1:text-3xl prose-h2:text-2xl prose-h3:text-xl prose-a:text-blue-600 prose-img:rounded-xl">
              <ReactMarkdown>{markdown}</ReactMarkdown>
            </div>
          ) : (
            <div className="h-full flex flex-col items-center justify-center text-neutral-400 space-y-4">
              <div className="w-16 h-16 rounded-full border-2 border-dashed border-neutral-200 flex items-center justify-center">
                <span className="text-2xl">📝</span>
              </div>
              <p>Your beautiful lesson will appear here.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
